### PR TITLE
Improve ux

### PR DESCRIPTION
**Pull request by doozr**
Made the look 'n' feel nicer, added syntax highlighting and made the Jobs link to the current careers page rather than the BSkyB email address.

Incidentally corrected a handful of minor errors in the Pidl post.

### CODE REVIEW

**Comment by glenjamin** [comment]
Weirdly, I can't accept this. Might need @robtuley to change perms.

**Comment by robtuley** [comment]
Thanks @doozr -- a definite improvement although still with some work to do. I'll merge in, @adamhepton promised some help with the styling too so perhaps he can help evolve too. 

@glenjamin  -- I've setup a separate engineering site contributors team on our account which is the write access group for this repo; and am populating it with those volunteering to be part of site working group. You want in?

**Comment by glenjamin** [comment]
Depends what you'd need me to do 😀

Happy to technical review, and in theory I'd like to write about what we're doing here, but no idea where I'll get time!

**Comment by doozr** [comment]
I don't pretend it's anything more than a quick CSS hack, but getting it
on-brand and with code full width and syntax highlighted seemed like a good
idea ;)

**Comment by robtuley** [comment]
I would make a terrible designer, I think my ideal page is basically high-contrast quality text; getting the syntax highlighting makes a good difference though.

@glenjamin concentrate on making time for contribution rather than technical review, have a few volunteers already for the latter.

**Pull request merged**
