### PR TITLE
Es6 react training

### PR DESCRIPTION
**Pull request by ls12styler**
Don't merge yet :)

### CODE REVIEW

**Comment by glenjamin** [comment]
What's this waiting on @ls12styler?

**Comment by ls12styler** [comment]
@glenjamin Nothing now. Feel rebased off master. Feel free to merge :)

**Comment by TomNomNom** [comment]
@ls12styler would be good to add some learnings from the training as a way to conclude the post :)

**Comment by ThomasLomas** [comment]
Is this post still going to be merged? because it now has a conflict

**Comment by cmbuckley** [comment]
@ThomasLomas I think @TomNomNom’s comment is valid; it could do with a summary. @ls12styler care to rebase and add the key learnings?

**Comment by ls12styler** [comment]
Apologies. I've not had any time write up a conclusion/fix conflicts. It's not being forgotten, but I'll try and find some time this week.

**Pull request closed without merging**
