### PR TITLE
[resolves #47] Category Navigation

### LINKED ISSUE #47: Navigate by post category
It would be useful to be able to navigate by post category, or filter posts based on the category they belong to. Posts are already tagged appropriately so shouldn't be too difficult to implement.

### PR DESCRIPTION
**Pull request by adamblanchard**
- Added automatic generation of category pages
- Updated references to a posts category to link to the correct category page
- Added a "Categories" sidebar box for navigation

### CODE REVIEW

**Comment by adamhepton** [comment]
Thanks for the work, Adam.  Just a couple of things after a functional review (I or someone else can review the code once these are sorted):

1. Your branch needs to be up-to-date with skybet:master - there are some conflicts (not insurmountable but definitely needs resolving)
2. Tags with spaces in them (such as "Big Data" or "UI Engineering") don't go through to the category page.
3. "UI Engineering" has become "Ui Engineering" following automatic tag creation.
4. I am going to point @FirsRdJnr towards the styling of the categories section: I'm sure we can do something nice with Flexbox to make them distribute visually a bit nicer (but we can always follow up with that, it's not going to stop it going in as-is)

Either have these fixed up yourself, or ask in here and we can all pitch in.  Thanks again :+1:

**Comment by adamhepton** [comment]
There's a bit of confusion in there - the links to the categories are all broken now, they seem to be putting the whole link as the href itself - is there something computing it as a link and that's being used instead of just the slug?

**Comment by adamblanchard** [comment]
Sorry Adam, that last commit yesterday was a bit premature.

Anyway, it's now up to date with master, tags with spaces are now supported, and the capitalisation of categories is now correct.

Interestingly, between my first bundle install and the last, the capitalisation of categories from site config has changed. Previously they all came out of config lower case. They are working correctly for me now anyway.

**Comment by adamhepton** [comment]
All looks good in terms of both functionality and structure to me - welcome to the contributors list!

**Pull request merged**
