### PR TITLE
Scaling Agile talk video (don't merge yet)

### PR DESCRIPTION
**Pull request by glenjamin**
Putting this up for early review, need some input from a few other stakeholders before merging.

### CODE REVIEW

**Comment by glenjamin** [comment]
Just waiting on @robtuley to get the youtube upload onto a company-owned account.

Would appreciate any comments on the text

**Comment by robtuley** [comment]
I've already uploaded the video here:
https://www.youtube.com/watch?v=aGav01xfgZQ

And now you're a manager on the SB&G channel too. I've not yet tarted up the channel (added a banner image etc) but good enough to run with for this.

**Comment by glenjamin** [comment]
Cheers Rob, will add some video metadata and we should be good to go.

**Comment by glenjamin** [comment]
Ok, blogpost is now pointing at the new video location - ready for final review :)

**Comment by adamhepton** [comment]
Aside from a typo in the first line: "Initialy" should be spelled "Initially", this is good to go.  I'll merge, and change the typo in master (bad workflow practice, but easier all around...)

Cheers Glen

**Comment by glenjamin** [comment]
Thanks, good spot!

**Pull request merged**
