### PR TITLE
Update prism.js to 1.6.0

### LINKED ISSUE #175: Out of Date Prism
We appear to be using Prism.js v0.0.1. The latest version is v1.6.0.
Also, we're using the basic Prism.js, which I believe only supports the following languages:

* markup
* xml
* html
* mathml
* svg
* css
* clike
* javascript
* js

### PR DESCRIPTION
**Pull request by ant1441**
Resolves #175.
I haven't checked all the pages, but http://engineering.skybettingandgaming.com/2017/03/28/bettracker-typescript/ no longer highlights the "On first pass, we were presented with about 1800 errors all looking a bit like the following:", which is correct as that is not actually "bash".

I don't know what we want to do around supporting multiple languages.
We can just add languages individually (and globally), but that's a little messy

    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/components/prism-yaml.js" type="text/javascript"></script>

### CODE REVIEW

**Comment by adamhepton** [comment]
I've gone through and checked all articles that had more than a single line of syntax highlighting in them, and the bad news is that a lot of them are worse than they were before.

Articles that were previously highlighted properly that are no longer so:

2015-01-20-parsing-json-in-hive.md - SQL
2015-08-05-distributed-database-query-optimisation-lego.md - SQL
2015-09-09-opensourcing-pidl.md - Ruby, SQL
2015-10-21-zookeeper-locks-jruby.md - Ruby
2015-09-14-monitoring-virtual-sports.md - Go
2015-09-20-speeding-up-chef-search.md - Ruby
2016-02-03-kafka-cluster-sizing.md - Bash, Scala (the Scala isn't highlighting as it is)
2016-03-30-pyspark-phone-numbers.md - SQL, Python
2016-06-24-scripting-veritas-netbackup.md- Bash
2017-03-28-bettracker-typescript.md - Bash, TypeScript (TypeScript isn't highlighting as it is)

Articles that were previously highlighted properly and continue to be so:

2016-02-03-increasing-login-capcity-by-using-node-js.md - JS
2016-05-12-responsive-react-components.md - JS
2017-05-17-canvass.md - JS

Articles that were never properly highlighted and still aren't:

2016-03-01-delivery-pipelines-kitchen-chef-docker.md - Ruby
2016-05-05-aws-and-consul.md - Amazon LC Config file, Bash
2016-05-27-isomorphic-vegas.md - JS

**Comment by WheresAlice** [comment]
Some of the lack of highlighting is due to the code blocks not having a language named.  That's easily fixed by adding them in for languages that are already supported by our version of prism out of the box.

Some of the languages we are wanting to highlight are not included in the CDN version of prism though, and the languages included seem to vary depending on version.

As an alternative to adding extra files from the CDN for each language as discussed above (I haven't even tested that) we could download our own customised version of Prism from http://prismjs.com/download.html with the right languages ticked.  And if we're doing that we could also look at changing the theme and adding plugins for line numbering etc.  This would mean just two files - a js and a css file, nicely minified with just the languages we care about.

**Comment by adamhepton** [comment]
I recommend the download a customised bundle approach; I am not sure why - other than convenience - the initial Prism include was from CDN.

The articles that highlight correctly in the current build *should* have `language-xxxx` classes applied to the code blocks already - otherwise I'm not sure how they're working with the older version of Prism and the associated `::before` style which adds a little marker to the container with the syntax name - probably just need languages adding to the backticks for the last category (never been working) only.

**Comment by adamhepton** [comment]
Superseded by #179 - closing this.

**Pull request closed without merging**
