### PR TITLE
Use date in post permalinks

### PR DESCRIPTION
**Pull request by cmbuckley**
I also added `host: 0.0.0.0` to the config too, as I needed it in certain scenarios.

### CODE REVIEW

**Comment by cmbuckley** [comment]
@adamhepton @FirsRdJnr wanted you to have a look at this before I merged it

**Comment by adamhepton** [comment]
Yep, exactly what I had in mind to do it, just didn't get around to it. Thanks

**Comment by cmbuckley** [comment]
I've not actually merged it; I managed to confuse GitHub with a commit cock-up. Are you OK with it? I'll merge if so.

**Comment by adamhepton** [comment]
Heh, yeah.  Looks like the only one you merged was the jekyll serve, which wasn't really the point of this but HEY HO

**Comment by cmbuckley** [comment]
I confused myself with multiple remotes and pushed my cmbuckley:master up to skybet remote by accident, so I actually released both these changes (so this PR was marked as closed). I realised my mistake and rolled back. I'll re-merge this PR now

**Comment by cmbuckley** [comment]
Yes, it will be. I wanted to get it in as early as possible to affect a few people as possible.

**Pull request merged**
