### PR TITLE
Alas, I don't work here no more

### PR DESCRIPTION
**Pull request by lucymhdavies**
image

### CODE REVIEW

**Comment by heyitsols** [comment]
If I reject this PR does it mean you have to stay?

**Comment by lucymhdavies** [comment]
I think Hashi may have something to say about that 😂

**Comment by lucymhdavies** [comment]
Also... now I think of it I'm surprised the deploy-preview still works, given I own it still.

Who has a Netlify account, I can transfer https://app.netlify.com/sites/sbg-technology/ over to?

**Comment by heyitsols** [comment]
*begrudgingly raises hand*

**Comment by cmbuckley** [comment]
I regularly use netlify so happy to take this if you’d rather not @heyitsols

**Comment by heyitsols** [comment]
Saviour! Yes please @cmbuckley

**Comment by lucymhdavies** [comment]
Sure thing. Just let me know your Netlify username, and I'll transfer over ownership :)

**Comment by cmbuckley** [comment]
My Nelify username is cmbuckley; I thought you could do it by going to https://app.netlify.com/teams/sbg-technology/members/new and adding my email address (chris@cmbuckley.co.uk), but I've a feeling that will try to bill you when you do that.

**Comment by lucymhdavies** [comment]
That only works for teams. sbg-technology is a site. 🤷‍♀️ 

I've submitted the request to Netlify support for now.

**Comment by lucymhdavies** [comment]
@cmbuckley it should be transferred now. Lemme know if you've got access :)

**Comment by lucymhdavies** [comment]
image

**Comment by cmbuckley** [comment]
Looking good here! Farewell, and thanks for everything!

**Comment by lucymhdavies** [comment]
image

**Pull request merged**
