### PR TITLE
Agile Efficiency Post

### PR DESCRIPTION
**Pull request by adamblanchard**
Publishing on behalf on Richard Woodhead

### CODE REVIEW

**Comment by adamhepton** [comment]
So, this is an odd one.  I have a few grammatical points to bring up which usually I would say we should address, but in the spirit of the article itself I wonder whether we should publish as-is?  After all, the theme of the article is clearly around “don’t waste our time on the things that don’t matter when the bulk of stuff is enough” and by fixing up the grammar/spelling etc, are we not actually going against the theme of the article?

I’ll leave my notes here, which I compiled as-I-read: if I’d read it through and then found the areas, I probably wouldn’t have done them.

There are a few ellipses (…) that are dotted about - but there should only ever be one of them in a sentence.  It’s perfectly OK to type them as three periods, typographically speaking, on the web.

The structure is fine for speech, but in written form, the usage of fragments is not so readable: for example, I’d bring the “You may be able to relate” into the end of the previous paragraph rather than hanging as a paragraph of its own: it would be a perfectly good emphasis to make during a spoken presentation but in written, it doesn’t flow properly.

During the list on the “occurred to me” paragraph, I’d change the sentence to “It occurred to me: in a world of MVP, just in time, hack days and short feedback loops - is the requirement for…” to make it more readable and have clearer definition between the ideas.

"5 time more efficient” should be “five times more efficient” - numbers less than 10 are expressed in written form in English.

"re writing” should have a hyphen in the penultimate paragraph.

“covert” in the last paragraph should be “covet"

One thing I would say as a comment on the piece itself, though, is that people have different learning styles and biases about value: one person can think that putting in effort to ensure detail is overpolishing, another can perceive someone who has not as slapdash - and neither are wrong, it’s just different personal projections.

**Comment by WheresAlice** [comment]
The post filename has the month and date the wrong way round.

**Comment by ls12styler** [comment]
@adamblanchard: Do you still want to publish this post?

**Comment by adamblanchard** [comment]
@ls12styler I will chase the author

**Pull request closed without merging**
