### PR TITLE
[Resolves #51] Updated gemfile to include github-pages gem to manage our dependencies

### LINKED ISSUE #51: Dependencies differ from those used by Github Pages
We should use the github-pages gem to manage our dependencies for jekyll so we can be sure what we see generated locally will be the same as what we see live.

https://help.github.com/articles/using-jekyll-with-pages/#installing-jekyll

### PR DESCRIPTION
**Pull request by adamblanchard**
I've tested this on a fresh local install on OSX using RVM and ruby version 2.2.4-dev by running bundle install. Everything seems to be working. Would be good if someone else could test this too especially if on a different environment

### CODE REVIEW

**Comment by adamblanchard** [comment]
I'll fix that conflict before tomorrow, apologies

**Comment by adamhepton** [comment]
Have you tried raking the site itself?  Aside from having to run bundler with `ARCHFLAGS="-arch x86_64" bundle install` to get it installed, when I rake, I have a problem with jekyll-feed:

`/Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- jekyll-feed (LoadError)`

**Comment by adamhepton** [comment]
FWIW, those issues are when running on OSX system-default ruby.  Running within RVM (2.1.1) has no problems at all.  Probably the right thing to do is implement, and update the README to say that we recommend running in rvm.

**Comment by adamblanchard** [comment]
I didn't run into the ARCHFLAGS thing on either system ruby or rvm. Should I have seen an error?

Before I used RVM, I did see the second issue. This is because it's still trying to use jekyll 3.0.1 which has been installed globally from the previous bundle install. Once removing these old gems it installed and used the new versions correctly.

**Comment by ThomasLomas** [comment]
Been having some issues with trying to get `skybet:master` running locally using `ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]` installed via rvm. Tried the ARCHFLAGS too with no luck.

`redcarpet (3.3.3)`, `pygments.rb (0.6.3)` and `rouge (1.10.1)` all installed (Googling showed this fixing other people's issues)

```
rake --trace
** Invoke default (first_time)
** Invoke preview (first_time)
** Invoke clean (first_time)
** Execute clean
rm -rf _site
** Execute preview
jekyll serve --watch
Configuration file: /Users/---/Documents/skybet.github.io/_config.yml
            Source: /Users/---/Documents/skybet.github.io
       Destination: /Users/---/Documents/skybet.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Dependency Error: Yikes! It looks like you don't have redcarpet or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- redcarpet' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2015-12-09-when-hadoop-tools-disagree.md':
                    redcarpet
  Liquid Exception: redcarpet in feed.xml
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    redcarpet
```

With that said `bundle install` and `rake` worked first time with no problems when using `adamblanchard:github-pages-dependencies`

:+1:

**Comment by glenjamin** [comment]
You'll need to use `bundle exec` to run things after doing `bundle install` to make sure you get the right gems available.

**Comment by ThomasLomas** [comment]
Assuming `bundle exec rake`? As `bundle exec` says `exec needs a command to run`

If so, same issue on master :cry:

**Comment by glenjamin** [comment]
Ah, the `Gemfile` on master seems to be missing some dependencies.

**Comment by ThomasLomas** [comment]
Ah fair enough, guess i'll wait till this is merged in

**Pull request merged**
