### PR TITLE
Revert "[resolves #47] Category Navigation"

### LINKED ISSUE #47: Navigate by post category
It would be useful to be able to navigate by post category, or filter posts based on the category they belong to. Posts are already tagged appropriately so shouldn't be too difficult to implement.

### PR DESCRIPTION
**Pull request by adamhepton**
Reverts skybet/skybet.github.io#48

Github Pages don't support custom plugins, whoops!

### CODE REVIEW

**Comment by glenjamin** [comment]
If we do want to go more custom, we can have travis do the build and publish a pre-built site to pages instead.

**Comment by adamblanchard** [comment]
I figured either that or host it somewhere else. If we pre-generated the site and therefore lose the magic step that github does, what are the benefits of using github pages to host it?

**Comment by glenjamin** [comment]
Free and zero operational overhead and big sells IMO

**Comment by adamblanchard** [comment]
Yeah, even with the added cost of pre-generating/travis, pages still has a much smaller overhead doesn't it

**Pull request merged**
