### PR TITLE
Jmeter for Impala performance testing

### PR DESCRIPTION
**Pull request by WheresAlice**
A short but useful post on how to measure impala performance using JMeter.  Mostly because I didn't realise this was possible until I tried it and because we're low on number of posts at the moment.

Feel free to ask for more details on anything specific.

### CODE REVIEW

**Comment by medains** [comment]
Nice brief post with some useful info in - I like it.  I'd be tempted to trim the jmeter screenshots down a bit though.

**Comment by WheresAlice** [comment]
I've cropped the screnshots

**Comment by GomezIker** [comment]
Is it a good idea to show the JDBC URL conenction details on the screenshot? just out of curiosity...

**Comment by WheresAlice** [comment]
I don't think the connection string gives away anything sensitive, and the host is a temporary HAProxy instance.

**Pull request merged**
