### PR TITLE
How to dba

### PR DESCRIPTION
**Pull request by WheresAlice**
As discussed on Slack, I know the photos are all terrible quality, but they do add to the story.

Can somebody proof-read and tell me how I can improve this post please?

### CODE REVIEW

**Comment by WheresAlice** [comment]
As discussed on Slack, I should add more of a personal closing and get the date changed to go after Glen's post.

**Comment by WheresAlice** [comment]
OK, good to go on the 17th once @glenjamin's post is published.

**Comment by adamhepton** [comment]
I've made some grammatical amends to the post (and renamed to the correct date), Alice.  I'll lob you a pull request for you to pour your eye over, please, Alice.  Really enjoyed the post, though, probably my favourite one yet, and I have very little interest in databases.

**Comment by adamhepton** [comment]
Not sure if I said "Alice" enough during that comment :P

**Comment by WheresAlice** [comment]
I can honestly say this is the first time I've approved a pull request on a pull request.

**Pull request merged**
